version: '3.8'

services:
  # Base de Datos Principal (PostgreSQL + PostGIS)
  # Usamos la imagen de PostGIS directamente para soportar mapas y geolocalización.
  db:
    image: postgis/postgis:15-3.3
    container_name: paws_db
    restart: always
    environment:
      POSTGRES_USER: paws_user
      POSTGRES_PASSWORD: paws_secret_password
      POSTGRES_DB: paws_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paws_network

  # Cache y Mensajería (Redis)
  # Crucial para el Chat en tiempo real y validar la Blacklist rápidamente.
  redis:
    image: redis:alpine
    container_name: paws_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paws_network

  # (Opcional) Interfaz visual para ver la BD sin instalar nada extra
  pgadmin:
    image: dpage/pgadmin4
    container_name: paws_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@paws.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - paws_network

volumes:
  postgres_data:
  redis_data:

networks:
  paws_network:
    driver: bridge