services:
  # 1. BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: paws-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paws-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. CACHÉ (REDIS)
  redis:
    image: redis:alpine
    container_name: paws-redis
    restart: always
    ports:
      - "6379:6379"

  # 3. ALMACENAMIENTO (MINIO - S3 Compatible)
  minio:
    image: minio/minio
    container_name: paws-minio
    restart: always
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Consola Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # 4. BACKEND (TU APP GO)
  backend:
    build: . # Construye usando el Dockerfile en la carpeta actual
    container_name: paws-backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080" # Exponemos el puerto al exterior (Windows)
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: paws-db
      DB_SSL_MODE: disable  # <--- ¡IMPORTANTE! AGREGA ESTA LÍNEA
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      JWT_SECRET: "tu_secreto" 

volumes:
  postgres_data:
  minio_data: