# Static analysis options for Dart.
# Defines linter rules and analysis settings.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # For a full list of available lints, see:
    # https://dart.dev/lints
    #
    # You can customize rules here. For example:
    # avoid_print: false
    # prefer_single_quotes: true
